Check if kernels are actually installed

diff --git a/cryptboot-efikeys b/cryptboot-efikeys
--- a/cryptboot-efikeys
+++ b/cryptboot-efikeys
@@ -149,50 +149,55 @@ sign)
     fi
     echo "Signing file '$filename' with UEFI Secure Boot keys..."
     sbsign --key db.key --cert db.crt --output "$filename" "$filename"
-    # TODO: Unpack modules
     echo "Signing modules with UEFI Secure Boot keys..."
-    readarray -t LINUX_MODULES < <(/usr/bin/find /lib/modules/$(pacman -Q linux | sed 's/linux//;s/.arch/-arch/' | tr -d "[:space:]") -type f -name '*.ko*')
-    for ((i = 0; i < "${#LINUX_MODULES[@]}"; i++)); do
-        {
-            LINUX_MODULE="${LINUX_MODULES[$i]}"
-            zstd -d "${LINUX_MODULES[$i]}" -fq --rm
-            LINUX_MODULE="${LINUX_MODULE:0:-4}"
-            /usr/src/linux/scripts/sign-file sha256 db.key db.crt "$LINUX_MODULE"
-            zstd -z "$LINUX_MODULE" -fq --rm
-        } ||
-        {
-            echo "ERROR: modules couldn't be signed with UEFI Secure Boot keys"
-            exit 1
-        }
-    done
-    readarray -t LINUX_MODULES < <(/usr/bin/find /lib/modules/$(pacman -Q linux-lts | sed 's/linux-lts//' | tr -d "[:space:]")-lts -type f -name '*.ko*')
-    for ((i = 0; i < "${#LINUX_MODULES[@]}"; i++)); do
-        {
-            LINUX_MODULE="${LINUX_MODULES[$i]}"
-            zstd -d "${LINUX_MODULES[$i]}" -fq --rm
-            LINUX_MODULE="${LINUX_MODULE:0:-4}"
-            /usr/src/linux/scripts/sign-file sha256 db.key db.crt "$LINUX_MODULE"
-            zstd -z "$LINUX_MODULE" -fq --rm
-        } ||
-        {
-            echo "ERROR: modules couldn't be signed with UEFI Secure Boot keys"
-            exit 1
-        }
-    done
-    readarray -t LINUX_MODULES < <(/usr/bin/find /lib/modules/$(pacman -Q linux-zen | sed 's/linux-zen//;s/.zen/-zen/' | tr -d "[:space:]")-zen -type f -name '*.ko*')
-    for ((i = 0; i < "${#LINUX_MODULES[@]}"; i++)); do
-        {
-            LINUX_MODULE="${LINUX_MODULES[$i]}"
-            zstd -d "${LINUX_MODULES[$i]}" -fq --rm
-            LINUX_MODULE="${LINUX_MODULE:0:-4}"
-            /usr/src/linux/scripts/sign-file sha256 db.key db.crt "$LINUX_MODULE"
-            zstd -z "$LINUX_MODULE" -fq --rm
-        } ||
-        {
-            echo "ERROR: modules couldn't be signed with UEFI Secure Boot keys"
-            exit 1
-        }
-    done
+    if pacman -Qq "linux"; then
+        readarray -t LINUX_MODULES < <(/usr/bin/find /lib/modules/$(pacman -Q linux | sed 's/linux//;s/.arch/-arch/' | tr -d "[:space:]") -type f -name '*.ko*')
+        for ((i = 0; i < "${#LINUX_MODULES[@]}"; i++)); do
+            {
+                LINUX_MODULE="${LINUX_MODULES[$i]}"
+                zstd -d "${LINUX_MODULES[$i]}" -fq --rm
+                LINUX_MODULE="${LINUX_MODULE:0:-4}"
+                /usr/src/linux/scripts/sign-file sha256 db.key db.crt "$LINUX_MODULE"
+                zstd -z "$LINUX_MODULE" -fq --rm
+            } ||
+                {
+                    echo "ERROR: modules couldn't be signed with UEFI Secure Boot keys"
+                    exit 1
+                }
+        done
+    fi
+    if pacman -Qq "linux-lts"; then
+        readarray -t LINUX_MODULES < <(/usr/bin/find /lib/modules/$(pacman -Q linux-lts | sed 's/linux-lts//' | tr -d "[:space:]")-lts -type f -name '*.ko*')
+        for ((i = 0; i < "${#LINUX_MODULES[@]}"; i++)); do
+            {
+                LINUX_MODULE="${LINUX_MODULES[$i]}"
+                zstd -d "${LINUX_MODULES[$i]}" -fq --rm
+                LINUX_MODULE="${LINUX_MODULE:0:-4}"
+                /usr/src/linux/scripts/sign-file sha256 db.key db.crt "$LINUX_MODULE"
+                zstd -z "$LINUX_MODULE" -fq --rm
+            } ||
+                {
+                    echo "ERROR: modules couldn't be signed with UEFI Secure Boot keys"
+                    exit 1
+                }
+        done
+    fi
+    if pacman -Qq "linux-zen"; then
+        readarray -t LINUX_MODULES < <(/usr/bin/find /lib/modules/$(pacman -Q linux-zen | sed 's/linux-zen//;s/.zen/-zen/' | tr -d "[:space:]")-zen -type f -name '*.ko*')
+        for ((i = 0; i < "${#LINUX_MODULES[@]}"; i++)); do
+            {
+                LINUX_MODULE="${LINUX_MODULES[$i]}"
+                zstd -d "${LINUX_MODULES[$i]}" -fq --rm
+                LINUX_MODULE="${LINUX_MODULE:0:-4}"
+                /usr/src/linux/scripts/sign-file sha256 db.key db.crt "$LINUX_MODULE"
+                zstd -z "$LINUX_MODULE" -fq --rm
+            } ||
+                {
+                    echo "ERROR: modules couldn't be signed with UEFI Secure Boot keys"
+                    exit 1
+                }
+        done
+    fi
     sync
     ;;
 verify)
