Make logging more clear and various readability improvements

diff --git a/cryptboot b/cryptboot
--- a/cryptboot
+++ b/cryptboot
@@ -12,11 +12,16 @@
 # Fail on error
 set -e
 
-# Check if user is root
-if [[ "${UID}" -ne 0 ]]; then
-    echo "ERROR: You can only run this script as root"
-    exit 1
-fi
+# Define functions
+log_err() {
+    /usr/bin/logger -s -p local0.err <<<"${@}"
+}
+log_warning() {
+    /usr/bin/logger -s -p local0.warning <<<"${@}"
+}
+var_invalid_warning() {
+    log_warning "'${1}' is invalid in '${2}'."
+}
 
 # Default path for cryptboot.conf
 CONFIGURATION_FILE=/etc/cryptboot.conf
@@ -33,18 +38,19 @@ if [[ -f "${CONFIGURATION_FILE}" ]]; then
     # shellcheck source=/dev/null
     . "${CONFIGURATION_FILE}"
 else
-    echo "ERROR: ${CONFIGURATION_FILE} doesn't exist!"
+    log_err "'${CONFIGURATION_FILE}' doesn't exist."
     exit 1
 fi
 
-# Define functions
-var_invalid_warning() {
-    echo "WARNING: '${1}' isn't valid in '${2}'"
-}
+# Check if user is root
+if [[ "${UID}" -ne 0 ]]; then
+    log_err "You can only run this script as root."
+    exit 1
+fi
 
 # Check if EFI_DIR mountpoint exists
 if ! findmnt -sn "${EFI_DIR}" &>/dev/null; then
-    echo "ERROR: Couldn't find EFI System partition mountpoint '${EFI_DIR}', check your /etc/fstab"
+    log_err "Couldn't find EFI System partition mountpoint '${EFI_DIR}', check your '/etc/fstab'."
     exit 1
 fi
 
diff --git a/cryptboot-efikeys b/cryptboot-efikeys
--- a/cryptboot-efikeys
+++ b/cryptboot-efikeys
@@ -12,11 +12,34 @@
 # Fail on error
 set -e
 
-# Check if user is root
-if [[ "${UID}" -ne 0 ]]; then
-    echo "ERROR: You can only run this script as root"
+# Define functions
+log_err() {
+    /usr/bin/logger -s -p local0.err <<<"${@}"
+}
+log_warning() {
+    /usr/bin/logger -s -p local0.warning <<<"${@}"
+}
+check_arg() {
+    if [[ -z "${2}" ]]; then
+        log_err "You have to specify '[${1}]' as second argument."
+        exit 1
+    fi
+}
+check_cd() {
+    cd "${1:?}" ||
+        {
+            log_err "Could not 'cd' into '${1:?}'"
+            exit 1
+        }
+}
+exit_no_keys() {
+    log_err "There are no UEFI Secure Boot keys in '${1:?}'."
+    log_err "Please generate them first with '${2} create' and then enroll them with '${2} enroll'."
     exit 1
-fi
+}
+var_invalid_warning() {
+    log_warning "'${1}' is invalid in '${2}'."
+}
 
 # Default path for cryptboot.conf
 CONFIGURATION_FILE=/etc/cryptboot.conf
@@ -38,7 +61,7 @@ if [[ -f "${CONFIGURATION_FILE}" ]]; then
     # shellcheck source=/dev/null
     . "${CONFIGURATION_FILE}"
 else
-    echo "ERROR: ${CONFIGURATION_FILE} doesn't exist!"
+    log_err "'${CONFIGURATION_FILE}' doesn't exist."
     exit 1
 fi
 
@@ -48,33 +71,16 @@ chmod 700 "${EFI_KEYS_DIR:?}"/keys
 mkdir -p "${EFI_KEYS_DIR:?}"/backup/keys
 chmod 700 "${EFI_KEYS_DIR:?}"/backup/keys
 
-# Define functions
-no_keys_exit() {
-    echo "ERROR: There are no UEFI Secure Boot keys in '${EFI_KEYS_DIR:?}/keys'!"
-    echo "       Please generate them first with '${1} create' and then enroll them with '${1} enroll'"
+# Check if user is root
+if [[ "${UID}" -ne 0 ]]; then
+    log_err "You can only run this script as root."
     exit 1
-}
-check_cd_efi_keys_dir() {
-    cd "${EFI_KEYS_DIR:?}/keys" ||
-        {
-            echo "ERROR: Incorrect EFI_KEYS_DIR specified!"
-            exit 1
-        }
-}
-check_arg() {
-    if [[ -z "${2}" ]]; then
-        echo "ERROR: You have to specify [${1}] as second argument!"
-        exit 1
-    fi
-}
-var_invalid_warning() {
-    echo "WARNING: '${1}' isn't valid in '${2}'"
-}
+fi
 
 case "${1}" in
 create)
     # cd to EFI_KEYS_DIR/keys
-    check_cd_efi_keys_dir
+    check_cd "${EFI_KEYS_DIR:?}/keys"
 
     # Prompt to confirm erasure of UEFI Secure Boot keys in EFI_KEYS_DIR/keys
     for file in "${EFI_KEYS_DIR:?}"/keys/*; do
@@ -85,8 +91,8 @@ create)
             }
         DATE="$(date +"%FT%H-%M-%S")"
         BACKUP_PATH="${EFI_KEYS_DIR:?}"/backup/keys/"${DATE}".bak
-        echo "WARNING: UEFI Secure Boot keys in '${EFI_KEYS_DIR:?}/keys' already exists!"
-        echo "         A backup will be created at '${BACKUP_PATH:?}'."
+        log_warning "UEFI Secure Boot keys in '${EFI_KEYS_DIR:?}/keys' already exists."
+        log_warning "A backup will be created at '${BACKUP_PATH:?}'."
         read -rp "Do you want to delete them and generate new ones? (Type 'yes' in capital letters): " choice
         case "${choice}" in
         YES)
@@ -95,7 +101,7 @@ create)
             rm -rf "${EFI_KEYS_DIR:?}"/keys/*
             ;;
         *)
-            echo "ERROR: User aborted generating secureboot keys"
+            log_err "User aborted generating secureboot keys."
             exit 1
             ;;
         esac
@@ -166,11 +172,11 @@ create)
     sync
 
     # Notify user if script has finished successfully
-    echo "New UEFI Secure Boot keys created in '${EFI_KEYS_DIR:?}/keys'"
+    echo "New UEFI Secure Boot keys created in '${EFI_KEYS_DIR:?}/keys'."
     ;;
 enroll)
     # cd to EFI_KEYS_DIR/keys and check arguments
-    check_cd_efi_keys_dir
+    check_cd "${EFI_KEYS_DIR:?}/keys"
     PK="${2}"
     KEK="${3}"
     check_arg "PK.key" "${PK}"
@@ -179,11 +185,11 @@ enroll)
     # Check for keys
     if [[ "${ENABLE_OPROM}" == "true" ]]; then
         if ! [[ -f KEK.esl ]] || ! [[ -f db.esl ]] || ! [[ -f PK.auth ]] || ! [[ -f MS_OpROM_db.esl ]]; then
-            no_keys_exit "${0}"
+            exit_no_keys "${EFI_KEYS_DIR:?}/keys" "${0}"
         fi
     else
         if ! [[ -f KEK.esl ]] || ! [[ -f db.esl ]] || ! [[ -f PK.auth ]]; then
-            no_keys_exit "${0}"
+            exit_no_keys "${EFI_KEYS_DIR:?}/keys" "${0}"
         fi
     fi
 
@@ -243,17 +249,17 @@ enroll)
 
     # Notify user if script has finished successfully
     echo "UEFI Secure Boot keys in '${EFI_KEYS_DIR:?}/keys' enrolled to UEFI firmware."
-    echo "You should now sign your boot loader and reboot!"
+    echo "You should now sign your boot loader and reboot."
     ;;
 sign)
     # cd to EFI_KEYS_DIR/keys and check arguments
-    check_cd_efi_keys_dir
+    check_cd "${EFI_KEYS_DIR:?}/keys"
     FILENAME="${2}"
     check_arg "file" "${FILENAME}"
 
     # Check for keys
     if ! [[ -f db.key ]] || ! [[ -f db.crt ]]; then
-        no_keys_exit "${0}"
+        exit_no_keys "${EFI_KEYS_DIR:?}/keys" "${0}"
     fi
 
     # Sign FILENAME
@@ -268,13 +274,13 @@ sign)
     ;;
 verify)
     # cd to EFI_KEYS_DIR/keys and check arguments
-    check_cd_efi_keys_dir
+    check_cd "${EFI_KEYS_DIR:?}/keys"
     FILENAME="${2}"
     check_arg "file" "${FILENAME}"
 
     # Check for keys
     if ! [[ -f db.crt ]]; then
-        no_keys_exit "${0}"
+        exit_no_keys "${EFI_KEYS_DIR:?}/keys" "${0}"
     fi
 
     # List signatures in FILENAME
@@ -295,13 +301,11 @@ status)
     # Check if UEFI Secure Boot is active or inactive
     echo -n "UEFI Secure Boot status: "
     SECUREBOOT_ENABLED="$(od -An -t u1 --read-bytes=1 --skip-bytes=4 /sys/firmware/efi/efivars/SecureBoot-*)"
-    if [[ "${SECUREBOOT_ENABLED}" -eq 1 ]]; then
-        echo "ACTIVE"
-        exit 0
-    else
+    if ! [[ "${SECUREBOOT_ENABLED}" -eq 1 ]]; then
         echo "INACTIVE"
         exit 1
     fi
+    echo "ACTIVE"
     ;;
 *)
     # Print help
