Add set -e
This hasn't been tested yet, but I'm pretty sure that using it should now be valid.
I will include this in the next release anyways to make testing easier.

diff --git a/cryptboot b/cryptboot
--- a/cryptboot
+++ b/cryptboot
@@ -9,6 +9,9 @@
 # -----
 ###
 
+# Fail on error
+set -e
+
 # Check if user is root
 if [[ "${UID}" -ne 0 ]]; then
     echo "ERROR: You can only run this script as root"
